### ISSUE TITLE
Modal header not vertically centered on SkyUX4

### ISSUE THREAD

**Issue by Blackbaud-DanGrochmal** [blackbaud/skyux-modals#104]
### Expected behavior

Header items are vertically centered

### Actual behavior

![image](https://user-images.githubusercontent.com/39523611/86139526-dac2b480-babd-11ea-90c0-bf34b2a67240.png)

### Steps to reproduce

Create a SkyUX4 modal

**Comment by Blackbaud-SteveBrush** [comment]
Closing since the Modern theme has not been finished yet. Stay tuned!
