### ISSUE TITLE
Update confirm component demo and UX guidelines

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux-modals#124]
Review the demo buttons and update with more appropriate content based on internal feedback at on 10/24/19 at https://app.slack.com/client/T02BBN218/G46LZB3HT.

Also, update teh UX guidelines to make sure it's clear that `the objective here is to remove any calculation/mapping the user would have to do between positives/negatives and the actual outcome`.

**Comment by Blackbaud-AlexKingman** [comment]
@blackbaud-johnly The link doesn't seem to work for me any more. Do you remember what the end goal is here?

**Comment by blackbaud-johnly** [comment]
Addressed the docs portion of this with https://github.com/blackbaud/skyux2-docs/pull/995.

**Comment by blackbaud-johnly** [comment]
Alex and I talked offline about this, but just in case this doesn't get done anytime soon: The end goal here is to update the button labels to follow our guidance to use labels that make it clear what action is being taken. So for example, use `Delete` instead of `Yes` for a button after a "Do you want to do delete this?" prompt. Based on the current examples in the demo, I think we just need to change `OK` and `Yes` to `Continue` for the first four examples.

**Comment by blackbaud-johnly** [comment]
Addressed the demo portion in https://github.com/blackbaud/skyux2-demos/pull/51.
