### ISSUE TITLE
Modal does not have background color, can leave gaps between border and content

### ISSUE THREAD

**Issue by Blackbaud-MitchellThomas** [blackbaud/skyux-modals#127]
### Expected behavior
There is no blank gap between modal content and the modal border

### Actual behavior
There's a gap on the right and bottom.
![image](https://user-images.githubusercontent.com/9661547/91073802-93622b80-e609-11ea-9f3e-9bed17b95d21.png)

### Steps to reproduce
Open a modal on this page in the docs
https://developer.blackbaud.com/skyux/components/modal

If you do not see the gap, resize the window slowly, and it can be seen at various window sizes. It might be because of sub-pixel heights and widths of content.

### Severity
Low

### Impact
Low

[AB#1561205](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1561205)

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-MitchellThomas Which browser? Are you zoomed?

**Comment by Blackbaud-MitchellThomas** [comment]
@Blackbaud-SteveBrush, Chromium based edge. Default zoom level.
