### ISSUE TITLE
Modal focus flash on radio button selection

### ISSUE THREAD

**Issue by Blackbaud-DanGrochmal** [blackbaud/skyux-modals#130]
### Expected behavior

Nothing extraneous to happen when selecting a radio button

### Actual behavior

Selecting a radio button causes modal focus to flash

### Steps to reproduce

Open modal and click around on radio buttons
https://angular-owntus.stackblitz.io/

### Severity

low

### Impact

low

[AB#1570854](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1570854)

**Comment by Blackbaud-ToddYellin** [comment]
![image](https://user-images.githubusercontent.com/25795617/102232033-a781af80-3ebc-11eb-8bdd-e7e2cf3cc09e.png)
Related issue - there should be some way to avoid having the `sky-modal-content` section of the modal from being selectable, as shown in the screenshot.
