### ISSUE TITLE
Expand/collapse chevrons in tiled modals are misaligned

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux-modals#34]
### Expected behavior
Expand/collapse button should be middle aligned.

### Actual behavior
Button is bottom aligned.
![image](https://user-images.githubusercontent.com/13765813/55805012-93609a80-5aab-11e9-8cc6-52dddb920065.png)

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.0.5`
