### ISSUE TITLE
Clickable items within modals don't respond

### ISSUE THREAD

**Issue by Blackbaud-NickBarger** [blackbaud/skyux-modals#38]
### Expected behavior
Clickable items within modal content would respond appropriately.

### Actual behavior
After upgrading to 3.0.2, clickable items within modal content no longer respond.
Examples:
- Clicking links go nowhere
- Checking boxes or radio buttons do not select the item
- Clicking a File Drop area doesn't open the file browser window, but dragging and dropping a file still work

### Steps to reproduce
Create a modal with the following code:
```
<sky-modal>
  <sky-modal-content>
      <div class="sky-form-group">
          <a href="https://google.com" target="_blank">Test</a>
        </div>
  </sky-modal-content>
</sky-modal>
```
Serve the application, open the modal, and try to click the link. This won't work. Downgrade to 3.0.1 and retry. This will work.

**Comment by Blackbaud-AlexKingman** [comment]
@Blackbaud-NickBarger thanks for submitting this issue. We are working on a fix now.
