### ISSUE TITLE
Tab order from sky-modal-footer does not follow the same backwards as forwards

### ISSUE THREAD

**Issue by blackbaud-joshlandi** [blackbaud/skyux-modals#44]
### Expected behavior
If I've tabbed into a footer on an open modal, and then `Shift + Tab` backwards, i'd expect it either to move back to the modal content or the previous button in the footer (in the case where i've tabbed to `Cancel` when there's also a `Submit`).

In general tab order should go in reverse just as it does forwards.

### Actual behavior
If I've tabbed into a footer on an open modal, and then `Shift + Tab` backwards, it moves focus the `x` button in the header.

### Steps to reproduce
You can do it easily in the modal component page:
https://developer.blackbaud.com/skyux/components/modal
### Severity
Maybe Medium.  Depends how much we're worried about correct tab order.

### Impact
Low for my team, as we're not out in production at all.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.0.4`

**Comment by Blackbaud-ScottFreeman** [comment]
It looks like this issue fix has already been released, but I feel like the Shift+Tab order still isn't the same as the Tab order.  If you Tab you can go from the upper-right close to the modal content and then into the modal content.  If you are doing a Shift+Tab from the footer buttons, it doesn't go to the modal content.  Instead, it goes to the upper-right close button.  If you continue using Shift+Tab, it goes back and forth between the upper-right close button and the footer buttons.  You can't reach the modal content using Shift+Tab.

**Comment by Blackbaud-JackMcElhinney** [comment]
Looks like it works correctly on the StackBlitz demo but not on the docs page itself. Are you having this issue outside of the component docs?

**Comment by Blackbaud-ScottFreeman** [comment]
It is currently happening in the email spa after updating to `@skyux/modals` 3.0.5.  Perhaps there is an angular version that's different between the demo, our spa, and stackblitz.

**Comment by Blackbaud-ScottFreeman** [comment]
I ended up running `skyux install` to wipe out my local node_modules directory and that seems to have done the trick.  My local branch looks to have this feature working properly.  It really through me off that the demo wasn't working properly as well, but I guess that the demos aren't updated with the release like they often were with skyux2.  I'm guess that's because there are many repos with their own releases now.
