### ISSUE TITLE
Firefox > Unable to tab through hyperlinks inside modal content.

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux-modals#74]
### Expected behavior
I should be able to use the tab key to navigate between hyperlinks in a modal.

### Actual behavior
I can't! Buttons and the "X" button are still navigable though, strangely enough. Happens with Firefox on Mac. This doesn't seem to happen in Chrome.

### Steps to reproduce
Create a modal with a couple hyperlinks in it. Use Firefox. Do it.
![Screen Shot 2019-12-11 at 2 23 03 PM](https://user-images.githubusercontent.com/18354182/70653218-0a919400-1c22-11ea-86ad-41f47a6e4658.png)

**Comment by Blackbaud-SteveBrush** [comment]
This is due to a Firefox OS X setting that disables focusing for anchors. Thanks @Blackbaud-BobbyEarl !

**Comment by Blackbaud-BobbyEarl** [comment]
For posterity... 
- https://github.com/blackbaud/skyux2/issues/1319
- https://github.com/blackbaud/skyux2/issues/1291
