### ISSUE TITLE
Modal content padding not appropriate for vertical tabset content

### ISSUE THREAD

**Issue by Blackbaud-StewartStephens** [blackbaud/skyux-modals#76]
### Expected behavior
Vertical tabsets in a modal should fill the modal content area.

![image](https://user-images.githubusercontent.com/12860297/72378899-5089be00-36e0-11ea-87c9-8b0358dab728.png)

### Actual behavior
The div which wraps the sky-modal-content in sky-modal elements has the `sky-padding-even-large` class which applies 15px padding and makes the content look kind of strange.

![image](https://user-images.githubusercontent.com/12860297/72378788-1c160200-36e0-11ea-9c76-a5f0efd93e76.png)

### Steps to reproduce
Create a modal with a sky-vertical-tabset under the sky-modal-content element.

### Severity
Cosmetic.

### Impact
Cosmetic.

**Comment by Blackbaud-TrevorBurch** [comment]
Fixed in `skyux/tabs` version `3.2.4`
