### ISSUE TITLE
React-based event handlers are not functioning properly

### ISSUE THREAD

**Issue by Blackbaud-RobertDixon** [blackbaud/skyux-modals#81]
### Expected behavior
When using React on a modal, event handlers created with React will function properly.

### Actual behavior
Some of these event handlers are not firing.

### Steps to reproduce
In RENXT, go to Reporting > Report Builder.  Open a dashboard, then click the "Preview" button.  We have noticed the following failing to work:
- Sorting a table insight by clicking on a column header
- Clicking a link on a headline insight

These function properly in other parts of the application that aren't on a modal.

Let me know if you need links to specific environments/records (I'm guessing we try not to post that on public GitHub issues).

### Severity
Medium

### Impact
The specific problems we've seen are relatively minor and have workarounds, but are being noticed by clients.  We haven't done a full inventory of what functionality is missing for us.

We think we understand the root cause of this: 

- The link (or other click target) is set up through React, using a third party's library.
- According to info/docs I'm finding online, React handles event listeners by registering them all at the document level.  When the document handles those, it then delegates things out appropriately to the actual elements where the listeners were registered.  (I gather that the reason for this behavior is so React can ensure listeners are handled in a predictable order without browser differences, etc. playing a factor.)
- So, the click listener set up for the link actually gets fired when the document is handling the event.  Which works fine except...
- `skyux-modal-host` is between the link and the document in the event handling hierarchy.  It has an event handler for the click that does one thing:  call `stopPropagation()`.  Because of this, the document never gets the event, and because it's the document's click handler which actually matters, no action is taken by clicking the link.
- I've verified that removing the `stopPropagation()` call fixes the issue (though I'm sure it would introduce others).

**Comment by Blackbaud-AlexKingman** [comment]
@Blackbaud-RobertDixon this should be fixed in `@skyux/modals` version `3.2.0`. Also of note: if you are using any toasts or flyouts in conjunction with the modal, please upgrade those packages to the latest as well. Thanks!
