### ISSUE TITLE
Suggestion:  support "Close" as a standard (non-custom) confirm button

### ISSUE THREAD

**Issue by Blackbaud-BenLambert** [blackbaud/skyux-modals#99]
Just a suggestion to consider - the Confirm component supports a few standard options for the buttons to show:

- `OK`
- `YesCancel`
- `YesNoCancel`
- `Custom`

While it's very easy to do using `Custom`, I think having a simple `Close` option would be a nice enhancement to the standard buttons.

**Comment by Blackbaud-SteveBrush** [comment]
Spoke to Todd and we agree that the "OK" default is similar enough to "Close" that it would cause confusion if we made "Close" a first-class button. Thanks for the suggestion!
